# Config document
# This is used to configure the entire process, which components to use etc.
# With this config, it is easier to change and compare experimental setups.
#
# A side effect of using a config as pivot point is the hard dependency on it.
# Adding/removing features requires changes in the code, so to make that easier,
# there are indicators for where the respective parts of this config are used.
#
# This config is supposed to be well readable and easy to understand,
# hence the longer names.


### MODEL CONFIG ###
model:
    parts:
        # disabled parts become identity blocks or are omitted
        backbone: True
        ctm: True
        metric: True

    backbone:
        name: "resnet18"
        pretrained: True

    ctm:
        # block type and number can be specified for each component
        # implemented block types are found in ctm/ctm_model.py
        # for conv blocks, the number at the end specifies kernel size
        concentrator:
            structure:
                type: "conv2d3"
                num: 1
                activation: "relu"
                batchnorm: True

        projector:
            structure:
                type: "conv2d3"
                num: 1
                activation: "relu"
                batchnorm: True

        reshaper:
            structure:
                type: "conv2d3"
                num: 1
                activation: "relu"
                batchnorm: True

    metric:
        # depending on the chosen metric, this block can be flexible and contain
        # more or less info, adjust it accordingly
        name: "cosine"
        dim: 1

### MODE CONFIG ###
mode: "train" # from ["train", "test", "val"]

### HARDWARE CONFIG ###
device: "gpu" # from ["cpu", "gpu"]

### TRAIN CONFIG ###
train:
    batch_size: 64
    epochs: 5
    optimizer: "adam"

### DATASET CONFIG ###
dataset: 
    name: "miniimagenet"
    datatype: "img"
    channels: 3
    shape: [224, 224] # can be int or list of ints
    n_way: 10
    k_shot: 5

### LOGGING CONFIG ###
logging:
    log_on: False
