# Config document
# This is used to configure the entire process, which components to use etc.
# With this config, it is easier to change and compare experimental setups.
#
# A side effect of using a config as pivot point is the hard dependency on it.
# Adding/removing features requires changes in the code, so to make that easier,
# there are indicators for where the respective parts of this config are used.
#
# This config is supposed to be well readable and easy to understand,
# hence the longer names.


### MODEL CONFIG ###
model:
    parts:
        # disabled parts become identity blocks
        backbone: True
        ctm: True
        metric: True

    backbone:
        name: "resnet18"
        pretrained: True

    ctm:
        # block type and number can be specified for each component
        # implemented block types are found in ctm/ctm.py
        # for conv blocks, the number at the end specifies kernel size (nxn)
        concentrator:
            structure:
                type: "conv2d3"
                num: 1
                activation: "relu"
                batchnorm: True

        projector:
            structure:
                type: "conv2d3"
                num: 1
                activation: "relu"
                batchnorm: True

    metric:
        # the name key is mandatory and chooses the metric
        name: "pairwise"
        trainable: False
        # everything below is supplied to the metric module as kwargs
        p: 2.0

### HARDWARE CONFIG ###
device: "gpu" # from ["cpu", "gpu"]
#multigpu: True

### TRAIN OR TEST ###
train: True # if True then train, else test

## TRAINING CONFIG ##
training:
    epochs: 600
    optimizer:
        name: "adam"
        # optimizer kwargs below directly supplied to optimizer
        lr: 0.001
        weight_decay: 0.0005
    loss: "crossentropy"

### DATASET CONFIG ###
dataset: 
    name: "miniImagenet"
    #datatype: "img"
    channels: 3
    shape: [224, 224] # can be int or list of ints
    n_way: 2
    k_shot: 5

### LOGGING CONFIG ###
#logging:
#    log_on: False
